config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show]
  resources :reviews, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search', to: 'reviews#search'
  get "tag_search", to: "reviews#tag_search"
  resources :tags, only: [:index, :show] do
    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: "tag_id"
  has_many :reviews, through: :tag_maps
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
   @tag = Tag.all
  end
  
  def show
    @tag_list = Tag.all
    @tag = Tag.find(params[:id])
    @tag_review = @tag.reviews.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:tag_search])
    @tag_reviews = @tag_search.result(distinct: true)
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tag_list.html.erb
<% tag_list.each do |list| %>
  <%= link_to tag_path(list.id) do %>
  <div class="badge badge-dark"><%= list.tag_name %></div>
  <% end %>
<% end %>

app/views/tags/index.html.erb
<% @tag.each do |tag| %>
  <%= link_to tag_reviews_path(tag.id) do %>
  <div class="badge badge-dark"><%= tag.tag_name %></div>
  <% end %>
<% end %>

app/views/tags/show.html.erb
<div class="container my-4">
  <div class="row">
    
    <div class="col-lg-3 sidebar_fixed">
      <%= render "reviews/search_form", q: @q, tag_search: @tag_search %>
      <%= render "tags/tag_list", tag_list: @tag_list %>
    </div>
    
    <div class="col-lg-6">
      
      <div>
        <h1 class="btn btn-dark btn-lg"><%= @tag.tag_name %></h1>
      </div>
      
      <% @tag_review.reverse_each do |review| %>
        <!--各レビュー-->
        <%= render "reviews/review", review: review %>
      <% end %>
      
    </div>
    
  </div>
</div>