config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show]
  resources :reviews, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search', to: 'reviews#search'
  get "tag_search", to: "reviews#tag_search"
  resources :tags, only: [:index, :show] do
    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
    @new_review = Review.new(review_params)
    @new_review.score = Language.get_data(review_params[:body])
    @new_review.user_id = current_user.id
    tag_list = params[:review][:tag_name].split(nil) 
    #tag_list = params[:tag_name].split(nil) 
    if @new_review.save
      @new_review.save_tag(tag_list)
      redirect_to reviews_path
    else
      @tag_list = Tag.all
      @q = Review.ransack(params[:q])
      @tag_search = Tag.ransack(params[:tag_search])
      @tag_reviews = @tag_search.result(distinct: true)
      if params[:sort_select] == "new_arrival"
        @reviews = Review.order("created_at ASC")
      elsif params[:sort_select] == "topic_work"
        @reviews = Review.find(Favorite.group(:review_id).order('count(review_id) desc').pluck(:review_id))
      else
        @reviews = @q.result(distinct: true)
      end
      render :index
    end
  end

  def index
    @new_review = Review.new
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @tag_search = Tag.ransack(params[:tag_search])
    @tag_reviews = @tag_search.result(distinct: true)
    if params[:sort_select] == "new_arrival"
      @reviews = Review.order("created_at ASC")
    elsif params[:sort_select] == "topic_work"
      @reviews = Review.find(Favorite.group(:review_id).order('count(review_id) asc').pluck(:review_id))
    else
      @reviews = @q.result(distinct: true)
    end
  end
  
  def search
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:q])
    @tag_reviews = @tag_search.result(distinct: true)
  end
  
  def tag_search
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:q])
    @tag_reviews = @tag_search.result(distinct: true)
    @tag = Tag.ransack(params[:q])
    @tags = @tag.result(distinct: true)
    @reviews = []
    if @tags.length > 0
      @tags.each do |tag|
        tagmaps = TagMap.where(tag_id: tag.id)
        tagmaps.each do |tag_map|
          review = Review.find(tag_map.review_id)
          @reviews.push(review)
        end
      end
    end
    @reviews
  end
  
  def show
    @review = Review.find(params[:id])
    @post_tags = @review.tags
    @post_comment = PostComment.new
    @all_comments = PostComment.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review.tags.each do |tag|
      if tag.reviews.count == 1
        tag.destroy!
      end
    end
    @review.destroy!
    redirect_to reviews_path
  end
  
  private
  
  def review_params
    params.require(:review).permit(:cinema_title, :rate, :title, :body)
  end
  
  def search_params
    params.require(:q).permit!
    params.require(:t).permit!
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_error_dialog.html.erb
<div class="alert alert-danger"  role="alert">
  <%= validate.errors.count %>つのエラーがあります。
  <% validate.errors.full_messages.each do |message| %>
    <ul>
      <ui><%= message %></ui>
    </ul>
  <% end %> 
</div>

app/views/reviews/_favorite.html.erb
<% if review.favorited_by?(current_user) %>
  <div class="my-auto col-sm text-right">
    <%= link_to review_path(review.id) do %>
      <i class="far fa-comment-alt"></i> <%= review.post_comments.count %>
    <% end %>
    <%= link_to review_favorites_path(review), remote: true, method: :delete do %>
      <i class="fas fa-heart"></i> <%= review.favorites.count %>
    <% end %>
  </div>
  <% else %>
  <div class="my-auto col-sm text-right">
    <%= link_to review_path(review.id) do %>
      <i class="far fa-comment-alt"></i> <%= review.post_comments.count %>
    <% end %>
    <%= link_to review_favorites_path(review), remote: true, method: :post do %>
      <i class="far fa-heart"></i> <%= review.favorites.count %>
    <% end %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="card mx-auto my-4 shadow-lg">
  <%= link_to review_path(review.id), class: "text-dark" do %>
  <!--タイトルと評価-->
  <div class="card-header">
    <div class="row">
      <h3 class="col-sm-9"><%= review.cinema_title %></h3>
      <h3 class="col-sm-3 text-right"><%= review.rate %> /5.0</h3>
    </div>
  </div>
  <!--レビュー-->
  <div class="card-body">
    <p>Title:  <%= review.title %></p>
    <p class="alert alert-dark" role="alert"><%= review.body %></p>
  <% end %>
    <!--タグ表示-->
    <% review.tags.each do |tag| %>
      <%= link_to tag_path(tag.id) do %>
      <div class="badge badge-dark"><%= tag.tag_name %></div>
      <% end %>
    <% end %>
  </div>
  <!--諸機能-->
  <div class="card-footer">
    <div class= "row" >
      <!--投稿者・投稿日-->
      <div class="my-auto col-sm">by <%= review.user.name %> <%= review.created_at.to_s(:datetime_jp) %></div>
      <!--いいね・コメント-->
      <div id = "review_<%= review.id %>" >
        <%= render "reviews/favorite", review: review %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_search_form.html.erb
<!--映画検索-->
<div class="my-2">
  <%= search_form_for q, url:search_path do |f| %>
    <%= f.label :cinema_title, "映画検索" %>
    <div class="input-group">
      <%= f.search_field :cinema_title_cont, class:"form-control" %>
      <div class="text-right input-group-append">
        <%= f.submit "検索", class:"btn btn-outline-secondary" %>
      </div>
    </div>
  <% end %>
</div>
<div class="my-2">
  <!--タグ検索-->
  <%= search_form_for tag_search, url:tag_search_path do |f| %>
    <%= f.label :tag_name, "Tag検索" %>
    <div class="input-group">
      <%= f.search_field :tag_name_cont, class:"form-control" %>
      <div class="text-right input-group-append">
        <%= f.submit "検索", class:"btn btn-outline-secondary" %>
      </div>  
    </div>
  <% end %>
</div>

app/views/reviews/_sort.html.erb
<%= form_with model:sort, url: reviews_path, local:true, method: :get do |sort| %>
  <div class="input-group">
    <%= sort.select :keyword, [ ["新着", "new"],["人気", "likes"] ], {}, class:"form-control" %>
    <div class="text-right input-group-append">
      <%= sort.submit "Save", class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <%#= sort.radio_button :keyword, :new %>
  <%#= sort.label :keyword, "新規", {value: :new, style: "display: inline-block;"} %>
  <%#= sort.radio_button :keyword, :likes %>
  <%#= sort.label :keyword, "人気", {value: :likes, style: "display: inline-block;"} %>
<% end %>

app/views/reviews/index.html.erb
<div class="container my-4">
  <div class="row">
    <!--サイドバー-->
    <div class="col-lg-3 sidebar_fixed">
      <%= render "search_form", q: @q, tag_search: @tag_search %>
      <%= render "tags/tag_list", tag_list: @tag_list %>
    </div>
    
    <!--レヴュー-->
    <div class="col-lg-6">
      <div class="d-flex justify-content-between">
        
        <div>
          <h1>Review</h1>
        </div>
        
        <div class="my-auto">
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-secondary active">
              <%= link_to "新着", reviews_path(sort_select: "new_arrival"), class:"text-white" %>
            </label>
            <label class="btn btn-secondary">
              <%= link_to "人気", reviews_path(sort_select: "topic_work"), class:"text-white" %>
            </label>
          </div>
          
          
        </div>
        
      </div>
      <!--バリデーション-->
      <% if @new_review.errors.any? %>
        <%= render "error_dialog", validate: @new_review %>
      <% end %>
      <!--新規投稿-->
      <%= form_with model:@new_review, local:true do |f| %>
      <div class="card mt-4 shadow-lg">
        <div class="card-body">
          
          <div class="form-group">
            <div class="row">
              
              <div class="col-sm-9 text-left">
                <%= f.text_field :cinema_title, placeholder:"Cinema Title", class:"form-control" %>
              </div>
              
              <div class="col-sm-3 text-right">
                <%=f.select :rate, [["rate",0],["5",5],["4",4],["3",3],["2",2],["1",1]], {}, class:"form-control" %>
              </div>
              
            </div>
          </div>
          
          <div class="form-group">
            <%= f.text_field :title, placeholder:"Title", class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.text_area :body, placeholder:"Body", class:"form-control" %>
          </div>
          <% if user_signed_in? %>
          <div class="row">
            <div class="col-sm-9">
              <%= f.text_field :tag_name ,placeholder:"Tag1 tag2 tag3", class:"form-control" %>
            </div>
            <div class="col-sm-3 text-right">
              <%= f.submit "Post", class:"btn btn-outline-secondary form-control" %>
            </div>
          </div>
          <% else %>
          <div class="text-right">
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-secondary" %>
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-secondary" %>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
      <!--投稿一覧-->
      <% @reviews.reverse_each do |review| %>
        <!--各レビュー-->
        <%= render "review", review: review %>
      <% end %>
    </div>
    
    <div class="col-lg-3">
      
    </div>
    
  </div>
    
    
</div>

app/views/reviews/search.html.erb
<div class="container my-4">
  <div class="row">
    
    <div class="col-lg-3 sidebar_fixed">
      <%= render "search_form", q: @q, tag_search: @tag_search %>
      <%= render "tags/tag_list", tag_list: @tag_list %>
    </div>
    
    <div class="col-lg-6">
      
      <div class="d-flex justify-content-between">
        
        <div>
          <h1>映画検索</h1>
        </div>
        
        <!--<div class="col-lg-4 my-auto">-->
        <!--  <%#= render "sort", sort: @sort %>-->
        <!--</div>-->
        
      </div>
      
      <% @review.reverse_each do |review| %>
        <%= render "review", review: review %>
      <% end %>
      
    </div>
    
  </div>
</div>

app/views/reviews/show.html.erb
<div class="container col-lg-4">
  
  <div class="card mx-auto my-4 shadow-lg">
    
    <div class="card-header">
      <div class="row">
        <h3 class="col-sm-9"><%= @review.cinema_title %></h3>
        <h3 class="col-sm-3 text-right"><%= @review.rate %> /5.0</h3>
      </div>
    </div>
    
    <div class="card-body">
      <p>Title:  <%= @review.title %></p>
      <p class="alert alert-dark" role="alert" ><%= @review.body %></p>
      <% @review.tags.each do |tag| %>
        <%= link_to tag_path(tag.id) do %>
        <div class="badge badge-dark"><%= tag.tag_name %></div>
        <% end %>
      <% end %>
    </div>
    
    <div class="card-footer">
      <div class= "row" >
        <!--投稿者・投稿日-->
        <div class="my-auto col-sm">by <%= @review.user.name %> <%= @review.created_at.to_s(:datetime_jp) %></div>
        <div class="my-auto col-sm text-right">
          <% if @review.user == current_user %>
          <%= link_to "削除", review_path(@review), method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
    
  </div>
  
  <% if @post_comment.errors.any? %>
    <%= render "reviews/error_dialog", validate: @post_comment %>
  <% end %>
  <!--コメント投稿-->
  <div class="card mx-auto my-4 shadow-lg">
    <div class="card-body">
      <%= form_with(model:[@review, @post_comment], local: true) do |f| %>
      <div class="form-group">
        <%= f.text_area :comment, rows:'2',placeholder: "コメントをここに", class:"form-control" %>
      </div>
      <div class="text-right">
        <%= f.submit "Post a comment", class:"btn btn-outline-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
  <!--コメント一覧-->
  <!--<p>Comment</p>-->
  <% @review.post_comments.each do |post_comment| %>
  <div class="card mx-auto my-4 shadow-lg">
    <div class="card-body">
      <p class="alert alert-secondary" role="alert"><%= post_comment.comment %></p>
    </div>
    <div class="card-footer my-auto">
      <div class="row">
        <div class="col-sm">
          by <%= post_comment.user.name %>
          <%= post_comment.created_at.to_s(:datetime_jp) %>
        </div>
        <div class="col-sm text-right">
          <% if post_comment.user == current_user %>
          <%= link_to "削除", review_post_comment_path(post_comment.review, post_comment), method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  
</div>

app/views/reviews/tag_search.html.erb
<div class="container my-4">
  <div class="row">
    
    <div class="col-lg-3">
      <%= render "search_form", q: @q, tag_search: @tag_search %>
      <%= render "tags/tag_list", tag_list: @tag_list %>
    </div>
    
    <div class="col-lg-6">
      
      <div>
        <h1 class="btn btn-dark btn-lg">tag検索結果</h1>
      </div>
      
      <% @reviews.reverse_each do |review| %>
        <%= render "review", review: review %>
      <% end %>
      
    </div>
    
  </div>
</div>