config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show]
  resources :reviews, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search', to: 'reviews#search'
  get "tag_search", to: "reviews#tag_search"
  resources :tags, only: [:index, :show] do
    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  
  validates :comment, presence: {message: "#未入力"}
  validates :comment, length: { maximum: 250, message: "#250字以内まで"}
  
end

app/models/review.rb
class Review < ApplicationRecord
   belongs_to :user
   has_many :post_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :tag_maps, dependent: :destroy, foreign_key: "review_id" #独自
   has_many :tags, through: :tag_maps #独自
   
   validates :cinema_title, presence: {message: "#映画タイトルが未入力です。"}
   validates :cinema_title, length: { maximum: 20, message: "#20字以内までです。"}
   validates :rate, numericality: {greater_than: 0, message: "#評価が入力されていません。"}
   validates :title, presence: {message: "#評価のタイトルが未入力です。"}
   validates :title, length: { maximum: 20, message: "#20字以内までです。"}
   validates :body, presence: {message: "#本文が入力されていません。"}
   validates :body, length: { maximum: 250, message: "#250字以内までです。"}
   validates :score, numericality: {greater_than: -0.7, message: "#文章が感情的になりすぎている可能性があります。"}
   
   def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
   end
   
   def save_tag(sent_tags)
      # current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
      # old_tags = current_tags - sent_tags
      # new_tags = sent_tags - current_tags
      
      # old_tags.each do |old|
      #    self.tags.delete Tag.find_by(tag_name:old)
      # end
      
      sent_tags.each do |sent|
         new_post_tag = Tag.find_or_create_by(tag_name:sent)
         TagMap.new(review_id: self.id, tag_id: new_post_tag.id).save
         #new_post_tag = self.Tag.find_or_create_by(tag_name:new)
         #self.tags << new_post_tag
      end
   end
   
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: "tag_id"
  has_many :reviews, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :review
  belongs_to :tag
  
  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reviews, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top]
  
  def after_sign_in_path_for(resource)
    reviews_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @review = Review.find(params[:review_id])
    favorite = current_user.favorites.new(review_id: @review.id)
    favorite.save
  end

  def destroy
    @review = Review.find(params[:review_id])
    favorite = current_user.favorites.find_by(review_id: @review.id)
    favorite.destroy
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
    @new_review = Review.new(review_params)
    @new_review.score = Language.get_data(review_params[:body])
    @new_review.user_id = current_user.id
    tag_list = params[:review][:tag_name].split(nil) 
    #tag_list = params[:tag_name].split(nil) 
    if @new_review.save
      @new_review.save_tag(tag_list)
      redirect_to reviews_path
    else
      @tag_list = Tag.all
      @q = Review.ransack(params[:q])
      @tag_search = Tag.ransack(params[:tag_search])
      @tag_reviews = @tag_search.result(distinct: true)
      if params[:sort_select] == "new_arrival"
        @reviews = Review.order("created_at ASC")
      elsif params[:sort_select] == "topic_work"
        @reviews = Review.find(Favorite.group(:review_id).order('count(review_id) desc').pluck(:review_id))
      else
        @reviews = @q.result(distinct: true)
      end
      render :index
    end
  end

  def index
    @new_review = Review.new
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @tag_search = Tag.ransack(params[:tag_search])
    @tag_reviews = @tag_search.result(distinct: true)
    if params[:sort_select] == "new_arrival"
      @reviews = Review.order("created_at ASC")
    elsif params[:sort_select] == "topic_work"
      @reviews = Review.find(Favorite.group(:review_id).order('count(review_id) asc').pluck(:review_id))
    else
      @reviews = @q.result(distinct: true)
    end
  end
  
  def search
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:q])
    @tag_reviews = @tag_search.result(distinct: true)
  end
  
  def tag_search
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:q])
    @tag_reviews = @tag_search.result(distinct: true)
    @tag = Tag.ransack(params[:q])
    @tags = @tag.result(distinct: true)
    @reviews = []
    if @tags.length > 0
      @tags.each do |tag|
        tagmaps = TagMap.where(tag_id: tag.id)
        tagmaps.each do |tag_map|
          review = Review.find(tag_map.review_id)
          @reviews.push(review)
        end
      end
    end
    @reviews
  end
  
  def show
    @review = Review.find(params[:id])
    @post_tags = @review.tags
    @post_comment = PostComment.new
    @all_comments = PostComment.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review.tags.each do |tag|
      if tag.reviews.count == 1
        tag.destroy!
      end
    end
    @review.destroy!
    redirect_to reviews_path
  end
  
  private
  
  def review_params
    params.require(:review).permit(:cinema_title, :rate, :title, :body)
  end
  
  def search_params
    params.require(:q).permit!
    params.require(:t).permit!
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
   @tag = Tag.all
  end
  
  def show
    @tag_list = Tag.all
    @tag = Tag.find(params[:id])
    @tag_review = @tag.reviews.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:tag_search])
    @tag_reviews = @tag_search.result(distinct: true)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @tag_list = Tag.all
    @q = Review.ransack(params[:q])
    @review = @q.result(distinct: true)
    @tag_search = Tag.ransack(params[:tag_search])
    @tag_reviews = @tag_search.result(distinct: true)
    @reviews_score = @user.reviews.average(:score)
    @like_count = 0
    @reviews.each do |review|
      @like_count += review.favorites.count
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaReview</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/cc648ee9c4.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    
     <header class="bg-dark text-white ">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          
          <a class="navbar-brand" href="/reviews"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "ホーム", reviews_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path(current_user.id), class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link text-white" %>
                </li>
              <% end %>
            </ul>
          </div>
          
        </div>
      </nav>
     </header>
    
    <main class="mb-auto">
      <%= yield %>
    </main>
    
    <footer class="bg-dark text-white">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4 pt-5 pb-5">
            <%= image_tag('footer_logo.png') %>
          </div>
          <div class="col-md-8 pt-5 pb-5 mt-3">
            <h6 class="text-white"></h6>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>